# Name for the workflow
name: Deploy API To GCP

# When to run the workflow
on:
  push:
    branches: [main]


env:
  PROJECT_ID: optimic




# Define the jobs to run
# jobs:
#   build:
#     name: Build Docker Image
#     runs-on: ubuntu-latest

  #   steps:


  # deploy:
  #   name: Deploy to Google Cloud Run
  #   needs: push # make this job depend on the push job



# https://www.youtube.com/watch?v=7hJlhcYDR68
